[package]
edition = "2021"
name = "wasm-cryptokey"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = {version = "0.2", features = ["xxx_debug_only_print_generated_code"]}
wasm-bindgen-futures = "0.4"
web-sys = {version = "0.3", features = ["CryptoKey"]}
